#!/bin/sh

# =============================================================================
# Script 2: Field Initialization
# -----------------------------------------------------------------------------
# This script prepares and initializes the flow fields before the main run.
# It assumes that the mesh has already been generated by '01_run_meshing.sh'.
#
# It performs these steps:
#   - Swaps in the '.init' dictionaries for a preliminary run.
#   - Runs the solver briefly to establish an atmospheric profile.
#   - Uses setFields to initialize specific regions.
#
# Usage: ./02_run_fieldInitialization.sh
# =============================================================================

# Change to the script's directory for robust execution
cd "${0%/*}" || exit 1

# Source the OpenFOAM functions for running applications
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

# --- FIELD INITIALIZATION ---

echo "--> Preparing case for field initialization..."
# Swap in the dictionaries for this specific initialization step.
cp ./system/controlDict.init ./system/controlDict
cp ./system/fvSolution.init ./system/fvSolution
cp ./constant/cloudProperties.init ./constant/cloudProperties

echo "--> Running the solver for initialization..."
# getApplication reads the solver name from the system/controlDict
runParallel $(getApplication)

mv log.foamRun log.foamRun0

echo "--> Setting specific field regions with setFields..."
runParallel setFields

# -----------------------------------------------------------------------------
echo
echo "FIELD INITIALIZATION SCRIPT COMPLETE."
echo "Fields have been initialized across the processor* directories."
echo "You can inspect the initial fields (e.g., alpha.water) in ParaView."
echo "Next, run ./03_run_simulation.sh"
# =============================================================================
