#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso multiphaseCompressibleMomentumTransportModels
OpenPDAC/Allwclean
wclean interfacialModels/dragModels/solidSolidDrag

#------------------------------------------------------------------------------
